# 🚫 禁止广告与埋点上报流量
DOMAIN-KEYWORD,ad.,REJECT
DOMAIN-KEYWORD,ads.,REJECT
DOMAIN-KEYWORD,log.,REJECT
DOMAIN-KEYWORD,track,REJECT
DOMAIN-KEYWORD,stat,REJECT
DOMAIN-KEYWORD,monitor,REJECT
DOMAIN-SUFFIX,appsflyer.com,REJECT
DOMAIN-SUFFIX,umeng.com,REJECT
DOMAIN-SUFFIX,bugly.qq.com,REJECT
DOMAIN-SUFFIX,talkingdata.net,REJECT
DOMAIN-SUFFIX,adjust.com,REJECT
DOMAIN-SUFFIX,crashlytics.com,REJECT